apiVersion: v1
kind: Pod
metadata:
  name: pod-with-limits
  labels:
    name: pod-with-limits
spec:
  containers:
  - name: pod-with-limits
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
