apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  match:
    - excludedNamespaces: ["kube-*"]
      processes: ["*"]
    # - excludedNamespaces: ["audit-excluded-ns"]
    #   processes: ["audit"]
    # - excludedNamespaces: ["audit-webhook-sync-excluded-ns"]
    #   processes: ["audit", "webhook", "sync"]
    # - excludedNamespaces: ["mutation-excluded-ns"]
    #   processes: ["mutation-webhook"]